### ISSUE TITLE
Found bug - local variable referenced before assignment 

### ISSUE THREAD

**Issue by thompsonsed** [svenevs/exhale#1]
Hi Stephen, 

I think I've found a bug and a solution. I get the error 
"unable to create the root api body: local variable 'has_nested_children' referenced before assignment. I solved this by moving line 1020 in exhale.py to after line 999.

Amazing work by the way, been waiting for something this intuitive that does exactly what I want for a while. 

Thanks, 

Sam

**Comment by svenevs** [comment]
Hi Sam,

Yes, good catch sorry about that!  Thanks for submitting the issue, I'm glad you've found this library intuitive enough to actually use it 🙃 

-Stephen
