### ISSUE TITLE
Parentheses in return type template fail Sphinx

### ISSUE THREAD

**Issue by nilsleiffischer** [svenevs/exhale#104]
This C++ snippet is not correctly handled by Exhale:

```cpp
// This fails because everything before the first opening parenthesis is
// stripped from the output
template <size_t N>
std::array<double, (N + 1)> broken_func();
```

It fails Sphinx with this error message:

```
reading sources... [ 58%] api/function_my__func_8hpp_1af3a81a9bfbf0ad5fb56e57f234727619                                          
Exception occurred:
  File "/Users/nlf/.virtualenvs/spectre/lib/python3.8/site-packages/sphinx/util/cfamily.py", line 291, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expecting "," or ")" in parameters-and-qualifiers, got "+". [error at 3]
  (N + 1)> broken_func()
  ---^
```

The snippet works correctly when replacing `(N + 1)` with `N`. Here's a minimal working example to reproduce the issue:

https://github.com/nilsleiffischer/sphinx-bugs/tree/master/issue_exhale_templates

I have verified that the issue is not in Sphinx or Breathe, since it works when using those two without Exhale and generating the documentation with Breathe's `.. autodoxygenindex::`.

This is my environment:

- Python 3.8.6
- Breathe (breathe-apidoc) 4.27.0
- sphinx-build 3.5.3
- Doxygen 1.8.17
- Exhale 0.2.3

**Comment by svenevs** [comment]
Thank you for the detailed report, very helpful!  I'm closing this as a "duplicate in disguise", see https://github.com/svenevs/exhale/issues/106#issuecomment-834218192

I am open to hacks as well but I don't think that's a good avenue forward pending that discussion.  Please re-open if you feel it's not actually the same bug!
