### ISSUE TITLE
Wrong filenames with underscore folders

### ISSUE THREAD

**Issue by chengts95** [svenevs/exhale#110]
When parsing the File Hierarchy of folders like "Interface_a" and "Interface_b", the generated `library_root.rst`  only preserve the name after the last underscore. 
File inputs:
![File inputs](https://user-images.githubusercontent.com/6616679/125254059-5487a380-e2b7-11eb-947c-01cfbf6f1bc2.png)
Generated doc:
![Generated doc](https://user-images.githubusercontent.com/6616679/125254034-4b96d200-e2b7-11eb-80ae-dbb1ff8830b6.png)

**Comment by svenevs** [comment]
Thank you for reporting, sorry for the long delay.  Offending code:

https://github.com/svenevs/exhale/blob/359fccbdb3240d767d1ccd9070339382429f5bb3/exhale/graph.py#L2215-L2226

Need to think about how to fix this one correctly...

**Comment by chengts95** [comment]
Thank you very much！
