### ISSUE TITLE
graphviz doesn't seem to work on the online docs

### ISSUE THREAD

**Issue by florianhumblot** [svenevs/exhale#151]
In the developer reference documentation a graph is supposed to appear at the bottom of the "Execution Flow" chapter.
This is the case in the "stable" version of the hosted docs: https://exhale.readthedocs.io/en/stable/reference.html#execution-flow 
but in the "latest" version, it doesn't get executed, and instead we see the body of the `..graphviz` directive: https://exhale.readthedocs.io/en/latest/reference.html#execution-flow

**Comment by svenevs** [comment]
Awesome, thanks so much for reporting this! I had no idea :scream:
