### ISSUE TITLE
Duplicate and incorrect node names when parsing nested types under specialized templates

### ISSUE THREAD

**Issue by emprice** [svenevs/exhale#156]
This is a bit niche, but I noticed I was getting incorrect output for something like

```cpp
template <size_t Ndim>
struct Cylindrical { };

template <>
struct Cylindrical<2>
{
    struct Coords
    {
        // cool code here...
    };

    // other nested constructs...
};
```

This is perfectly valid C++, but my (themed) Sphinx output was showing this:

![image](https://user-images.githubusercontent.com/3172578/160321745-a4c3cb36-71b0-4f4a-ab9f-4e3d774da9a4.png)

Instead of the actual nested types, it was repeating the name of the parent specialization, over and over. I tracked the issue down to [this line](https://github.com/svenevs/exhale/blob/master/exhale/graph.py#L2415) in the master branch. From what I can tell, the code as written assumes that only the last class or struct name is templated and splits the full name accordingly. I don't know if it's perfect, but simply replacing the assignment on the linked line with the following lines solves the problem for me:

```python
import re
p = re.compile(r'(([A-Za-z]\w*)(<[\w,\s<>]+>)?::)+(([A-Za-z]\w*)(<[\w,\s<>]+>)?)')
m = p.match(node.name)
title = m.group(4)
```

![image](https://user-images.githubusercontent.com/3172578/160322197-908a8bf7-f679-481a-948d-9cc5d6288c63.png)

The terrifying-looking RegEx above is supposed to match groups of names preceding the double colon as many times as necessary, including templates in the middle for each one, with the last one in its own group so it's easy to extract.

**Comment by svenevs** [comment]
Oh my, that's quite the bug there... Thanks for reporting and proposing a possible fix! IIRC the way I'm searching for things there was because of templates in the template parameters, I'll need to investigate a bit. There may be a more straightforward way to solve this without the scary regex using the parent name (?)

I'm without much free time this week (preparing for travel next week) but I will try and dig around soon. Please feel free to poke me if there's no movement by April 10th. Wanted to acknowledge the report though!

**Comment by florianhumblot** [comment]
Working on setting up the tests for this, but the fix seems to be possible without the regex.
Currently this seems to work too:
```py

                if node.name[-1] == ">": # this node ends on a template
                    title = "{cls}{templates}".format(
                        cls=node.name[:first_lt].split("::")[-1],  # remove namespaces
                        templates=node.name[first_lt:last_gt + 1]  # template params
                    )
                else:
                    last_lt = node.name.rfind('<')
                    last_member = node.name.rfind('::')
                    if last_lt > last_member: # template belongs to last type
                        title = "{cls}{templates}".format(
                            cls=node.name.split("::")[-1],  # remove namespaces
                            templates=node.name[first_lt:last_gt + 1]  # template params
                        )
                    else: # template doesn't belong to nested type
                        title = "{cls}".format(
                            cls=node.name.split("::")[-1] # remove the namespace
                        )
```

That is the replacement for lines 2415:2418 in graph.py as referenced by the OP.

<details>
<summary>input/output</summary>

```c++
template<size_t N>
struct Base {};

template <>
struct Base<2>
{
    struct InnerStruct {
        int a;
    };
    struct AnotherNestedStruct {
        double b;
    };
    char base_member;
    template<size_t M>
    struct InnerTemplatedStruct{
      char s;
    };
    template <>
    struct InnerTemplatedStruct<4>{
        bool tru;
    };
};

```

Generates:
![image](https://user-images.githubusercontent.com/31630192/161002922-7b1e1f3e-5bc3-4a66-92d2-45be773eae23.png)

</details>

Not quite as pretty as I'd like it to be, but it does seem to do the trick. 
I'll  try to make this a proper fix this weekend.

**Comment by svenevs** [comment]
[v0.3.2](https://pypi.org/project/exhale/0.3.2/) is at long last out and your issue should be resolved (the new test cases all format correctly in rendered html), if there is still a problem please link me to the code or project!
