### ISSUE TITLE
LaTeX in \f$ swallows \n newlines

### ISSUE THREAD

**Issue by drmoose** [svenevs/exhale#173]
The doxygen [`\n` command](https://www.doxygen.nl/manual/commands.html#cmdn) inside a `@param` normally works, but when it appears next to an equation ([`\f$`](https://www.doxygen.nl/manual/commands.html#cmdfdollar)), the resulting HTML doesn't include the paragraph breaks it ordinarily would.

```cpp
/**
 * This one will break because the math swallows the newline.
 * @param away The direction \f$\tan x\f$ \n in which you float.
 */
void something_with_parameters(float away);
```

Renders as

```html
<p><strong>away</strong> – The direction <span class="math notranslate nohighlight">\(\tan x\)</span> 
 in which you float. </p>
```

![image](https://user-images.githubusercontent.com/5732028/180567803-47cad771-6e2a-4358-9700-5947b3b742c9.png)

The `<linebreak/>` is preserved by Doxygen, though:

```xml
<parameterdescription>
<para>The direction <formula id="0">$\tan x$</formula> <linebreak/>
 in which you float. </para>
</parameterdescription>
```

And renders correctly in the Doxygen html output:

![image](https://user-images.githubusercontent.com/5732028/180567983-9e4f617b-750a-4526-8c1a-57870862dac5.png)

I've pushed up the project I used to generate this example [here on github](https://github.com/drmoose/exhale-newline-eating-bug). Screenshots were generated with Javascript blocked so mathjax rewriting the DOM wouldn't confuse the issue.

**Comment by svenevs** [comment]
Thanks for reporting @drmoose, sorry for the delay!  I transferred the issue to breathe at https://github.com/michaeljones/breathe/issues/856, don't worry about not asking for help on the right repo -- the stack involved and which tool does what is very confusing for everyone.

Exhale creates a bunch of `.rst` docs that in most places use the [breathe directives](https://breathe.readthedocs.io/en/latest/directives.html#directives).  This happens at a very early stage.  Then sphinx invokes the builder (html, pdf, ebup, etc), and during the build asks `breathe` to transform the rst directive such as `.. doxygenfunction:: foo` into the final output you see.

So for issues related to final html output, it's usually something going on with breathe.  But if there are problems on a `File` or `Namespace` page then that is probably exhale.

This repo is fairly low traffic, so if you have another error and don't know where to post it feel free to open here and I'll advise what I can or direct you to the best of my ability :slightly_smiling_face:

**Comment by drmoose** [comment]
:+1: It's slightly embarrassing because I _do_ know the difference (and even briefly looked at the source code of Breathe to see whether this was something obvious & i could fire off a quick PR instead of the issue) and _still_ posted to the wrong tracker because I can't keep the names straight. Thanks for the forward.
