### ISSUE TITLE
Allow root file to be excluded and set filename of hierarchy files

### ISSUE THREAD

**Issue by svenevs** [svenevs/exhale#176]
I have some questions about this.
For our project this is a breaking change.
We used those files directly in a toctree. Which is not possible anymore due to the `.include` suffix. Is it still possible to do this?

_Originally posted by @IceflowRE in https://github.com/svenevs/exhale/pull/136#issuecomment-1238722511_

Interesting. Until it was brought up I wasn't aware of or intending the original behavior. IIRC it means each directive gets processed twice just one page isn't linked to or something so the default of `.include` is going to be kept.

But it's easy to patch in a config value for `exhale_args` to just allow you to choose the file basename (string) so that you can restore the original behavior. Would that work?

**Comment by IceflowRE** [comment]
Of course that would work. Or just an option that wont add the `.include` suffix and do not generate the `rootFileName` file?
