### ISSUE TITLE
Package for pip

### ISSUE THREAD

**Issue by svenevs** [svenevs/exhale#3]
I initially thought it was more appropriate to have this be tracked like `conf.py`.  It's kind of a pain in terms of maintaining projects using `exhale`.  Package it up for more convenience.

1. Decide once and for all whether you are going to keep everything in one file (probably not necessary anymore).
    - I hate the packaging system though.
2. Start using releases via tags.
3. Going to need to create some sort of autotool so that people who `pip install exhale` can still use the `treeView` stuff.
    - Pull a `breathe` and wrap the `sphinx-quickstart` tool?  Sounds like a lot of work...

**Comment by svenevs** [comment]
It lives!  @thompsonsed and @kwf37 since you were "watching" the repo it leads me to believe you may have been using the single-file version.  Exhale redux is significantly more flexible, and hopefully a lot easier to use.  Advise updating to new version if you have the old one :wink:

**Comment by thompsonsed** [comment]
You are indeed correct! Thanks Stephen, will use the new version next time I update my documentation workflow.

Cheers,

Sam
