### ISSUE TITLE
Notice of future intent and requirements

### ISSUE THREAD

**Issue by svenevs** [svenevs/exhale#62]
Exhale is in "bugfix only" mode right now, I expect to be able to sit down and do the much needed rewrite this summer.  Please continue to open issues related to build errors, or explain features you would like to see in the future.  If it is a bug, a patch release can usually be obtained fairly easily.

Future requirements: Sphinx 2.0 is coming in soon, and will require python 3+.  I will be requiring sphinx>=2.0 with Exhale 1.0.  **I also intend to require python 3.6 or later**, this library needs a lot of string manipulation and f-strings make that much easier for me.  If python 3.6 will present significant challenges for you or your project please speak up / explain why obtaining 3.6 or later will be problematic.

**Comment by svenevs** [comment]
2.0 officially released.  Breathe may have trouble with some projects, if you have build errors like `TypeError: parse_declaration() missing 1 required positional argument: 'directiveType'` for the time being pin `Sphinx==1.8.5` for your docs builds.

**Comment by svenevs** [comment]
Update: please consider pinning your docs dependencies to `Sphinx>=2.0` and `breathe>=4.13`, breathe 4.13 now requires Sphinx 2.x or later, and you will get many useful fixes such as `using` directives rendering as expected among others.

None of this really affects exhale, the generated rst docs are all the same, the breathe backend of how signatures etc are created is what changed :tada:

**Comment by svenevs** [comment]
Worth updating this thread ... I have not abandoned this project, but until I make it out of thesis hell I can't justify getting into the (massive) rewrite that needs to happen in order to enable other people to contribute.

Small features can usually still be hacked in relatively quickly, and bugfixes should be possible to resolve.  Anything substantive, or anything that will conflict with future design plans, will continue to be on hold :confused:

**Comment by svenevs** [comment]
Officially these requirements are now in with https://github.com/svenevs/exhale/releases/tag/v0.3.0

Of course none of the actual meaningful changes are in, just the requirements via setup.

How do I feel about this project?  Well, if you could provide a one sentence description of the movie Cloud Atlas, then probably it would be that.  I will continue to try and improve things slowly, but the overwhelming amount of technical debt, mine and not mine, is often times traumatic.  If exhale works for you that's great!  I'm honestly shocked it still works.  If it doesn't work well enough for you, that's a shame.  But I did it all for free and you get what you pay for.

Maybe 1.x will happen one day.  That would be cool.

**Comment by mloskot** [comment]
Thank you for your hard work!
