### ISSUE TITLE
Run through non utf-8 encoded source code results in error

### ISSUE THREAD

**Issue by Zenahr** [svenevs/exhale#96]
I am working with a code-base encoded in ANSI. Changing the encoding to something like UTF-8 is currently not an option. However, I want to generate documentation via Breathe nonetheless.

Attempting a run generates following stack output:

```
lookup cache used 65536/65536 hits=1319859 misses=82153
finished...


Extension error:
Unable to execute 'doxygen': 'utf-8' codec can't decode byte 0xfc in position 175764: invalid start byte
make: *** [Makefile:26: html] Error 2
```

What steps do I need to take to make this work **without** changing the encoding of the source files? I thought about cloning the code-base temporarily and save it in utf-8 encoding and generate docs via Breathe on that but I hope there's an alternative to this approach.

---

I assume the `source_encoding` option inside _conf.py_ is related to Sphinx. I found [this](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-source_encoding) entry on the Sphinx docs website which doesn't show supported parameters nor the naming standard for them.

I've set `the source_encoding` parameter inside _conf.py_ to `mbsc` which, according to the Python docs is equivalent to ANSI. Still, the above stacktrace appears. 

---

Here's my Makefile:

```cmake

# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SPHINXPROJ    = ExhaleCompanion
SOURCEDIR     = .
BUILDDIR      = _build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile clean

clean:
	rm -rf doxyoutput/ api/
	# these are specific to the companion site, ignore this rm
	rm -f conf_extensions.rst conf_theme.rst
	@$(SPHINXBUILD) -M clean "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)


```

**Comment by Zenahr** [comment]
I might add that this error occurs even though all source files have been converted to utf-8 (for testing purposes).

**Comment by svenevs** [comment]
Hey!  Sorry, this semester is insane ... it looks like I messed up doxygen stuff or need to possibly allow you a way to pass flags to call doxygen with a different encoding?

https://github.com/svenevs/exhale/blob/58c6c771fe021d7487644a30c2575b3fcf1ae94b/exhale/deploy.py#L113

or

https://github.com/svenevs/exhale/blob/58c6c771fe021d7487644a30c2575b3fcf1ae94b/exhale/deploy.py#L135

may also be problems.  The stuff in `conf.py` is not relevant here, that's the sphinx side.  The `encoding` settings to `utf-8` in calling doxygen seem to be the most likely problem.  Are you setting any encoding stuff on doxygen configuration side?  Hopefully the above is helpful in tracking down and we can see what right way to fix it is

**Comment by Zenahr** [comment]
@svenevs Thank you! I guess I'll have to modify the source code a bit then? Maybe I'll get a PR out of it if I'm happy with it. A central setting like `source_code_encoding` = utf-8 | ansi | ... would be awesome which would then propagate it to all components (Sphinx, Doxygen).

**Comment by Zenahr** [comment]
I'll put the **solution** in here if I solve it and close this issue then.

**Comment by Zenahr** [comment]
@svenevs Changed following lines of code

```python
tempfile_kwargs = {"encoding": "utf-8"}
doxygen_input = bytes(doxygen_input, "utf-8")
```

to

```python
tempfile_kwargs = {"encoding": "mbsc"}
doxygen_input = bytes(doxygen_input, "mbsc")
```

The error message changed. Now resulting in this trace:

```
Generating XML output for file someheader.h
Running plantuml with JAVA...
lookup cache used 65536/65536 hits=1319859 misses=82153
finished...


Extension error:
Unable to execute 'doxygen': 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
make: *** [Makefile:26: html] Error 2
```

To me this looks like Doxygen does finish generating the api. What step specifically fails here? Also, I can't find out which file is causing this problem. Is there a way to make the log more verbose?

**Comment by Zenahr** [comment]
I used following steps this time:

1. Generate doxygen XML output via doxygen and a doxyfile. (Worked fine without any issues) (XML is in UTF-8 format)
2. Place XML into the folder which Breathe expects it to sit in
3. Set following option inside `config.py`:

`exhaleExecutesDoxygen=False`

Resulting trace:

```
make html      
Running Sphinx v3.2.1
loading pickled environment... done
WARNING: Exhale: `exhaleDoxygenStdin` ignored since `exhaleExecutesDoxygen=False`
[~] Exhale: adding tree view css / javascript.
[+] Exhale: added tree view css / javascript. 
[~] Exhale: parsing Doxygen XML.
(!) Exception caught while parsing:Traceback (most recent call last):
  File "OBFUSCATED_PATH\docs\env\src\exhale\exhale\graph.py", line 1076, in discoverAllNodes
    index_contents = index.read()
  File "C:\Python38\lib\codecs.py", line 701, in read
    return self.reader.read(size)
  File "C:\Python38\lib\codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 1331058: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OBFUSCATED_PATH\docs\env\src\exhale\exhale\deploy.py", line 394, in explode
    textRoot.parse()
  File "OBFUSCATED_PATH\docs\env\src\exhale\exhale\graph.py", line 1045, in parse
    self.discoverAllNodes()
  File "OBFUSCATED_PATH\docs\env\src\exhale\exhale\graph.py", line 1078, in discoverAllNodes
    raise RuntimeError("Could not read the contents of [{0}].".format(doxygen_index_xml))
RuntimeError: Could not read the contents of [OBFUSCATED_PATH\docs\doxyoutput\xml\index.xml].
make: *** [Makefile:26: html] Error 1
```
@svenevs Could it be that this issue is happening because we stream the doxygen output in as a bytestream? It's just a guess, I have no idea how this changes things related to encoding.

**Comment by svenevs** [comment]
Sorry for delay, things are not so good for me right now. AFAICT it's because of how I load things, should be fixable but I need to double check some things here and in breathe. It may be possible to unify encoding arguments, but it may be required or preferred to keep sphinx rst encoding and this separate.

Can you upload a zip here or something with files encoded in the format you are working with that ultimately will get a CC0 license for me to include in `testing/projects` folder? This will help me verify the changes I think I need to make.

Will be looking into this on Sunday but this project is a dangerous door for me to open right now.  If it can be fixed relatively quickly it will, otherwise I'll provide suggestions and you may need to work with a fork for now :confused:

**Comment by Zenahr** [comment]
@svenevs Hey svens. Sorry that this has been dragging on a while.
I think the doxygen part of it is fine actually. 

Doxygen successfully creates the XML output from the source files

```
Generating XML output for file lastfile.cpp
Generating XML output for file lastfile.h
Running plantuml with JAVA...
lookup cache used 65536/65536 hits=1319859 misses=82153
finished...


Extension error:
Unable to execute 'doxygen': 'utf-8' codec can't decode byte 0xfc in position 182836: invalid start byte
make: *** [Makefile:26: xml] Error 2
```

The error occurs in Sphinx I think. Even though it says "doxyge" in the stacktrace I don't really get it since running vanilla Doxygen over the source files works no problem.
I couldn't find the cause and since then moved away from Breathe in this particular case and settle with my custom documentation generation pipeline.
Since I don't think there will be any progress on this issue, I will close it.
