### ISSUE TITLE
Include inherited members in doxygenstruct

### ISSUE THREAD

**Issue by neel** [svenevs/exhale#97]
I want to have all the inherited members to be shown in the documentation of a struct shown with the `doxygenstruct` directive.

```
.. doxygenstruct:: StructName
   :members:
   :inherited-members:
```

The above produces error 

> WARNING: Error in "doxygenstruct" directive: unknown option: "inherited-members".

**Comment by svenevs** [comment]
Not entirely sure what status of this is, this has more to do with `breathe` / `doxygen` than this project (don't read that wrong, it's very confusing how all the pieces fit together!).

1. There is no `:inherited-members:` specifier.  See [`.. doxygenstruct::` docs](https://breathe.readthedocs.io/en/latest/directives.html#doxygenstruct).
2. It appears that you can get inherited members to show up if you are willing to do a little song and dance, but you may get an explosion of warnings and unreliable linkage.  Ref: https://github.com/michaeljones/breathe/issues/356
3. On the exhale side, you'll may need to get creative with the [breathe customization](https://exhale.readthedocs.io/en/latest/reference/configs.html#breathe-customization).  But it looks like using `:no-link:` is not preferred, in which case as long as you get (2) setup with the correct `doxygen` configs my understanding is you'll be good to go?

Hopefully that helps steer you in the right direction!
